### / 1 . - Petición para mostrar todos los productos
GET http://localhost:3000/products


###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "tipo_producto": "chaqueta",
    "precio": "100",
    "imagen": "x",
    "producto": "parka the north face"

}

###
PUT http://localhost:3000/products
Content-Type: application/json

{
    "id": "7",
    "tipo_producto": "chaqueta",
    "precio": "200",
    "imagen": "x",
    "producto": "parka the north face"
}

###
DELETE  http://localhost:3000/products/7
Content-Type: application/json


###
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "Carla", 
    "apellidos": "Verdejo", 
    "fecha_nacimiento": "1999-10-10",
    "email": "cvdj@gmail.com",
    "contraseña": "12345", 
    "rol": "vendedor", 
    "foto": "x",
    "nickname": "crv"
}

###
DELETE http://localhost:3000/users/3
Content-Type: application/json

###
PUT http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "Alba", 
    "apellidos": "Verdejo", 
    "fecha_nacimiento": "1998-10-10",
    "email": "cvdj@gmail.com",
    "contraseña": "12345", 
    "rol": "vendedor", 
    "foto": "x",
    "nickname": "crv"
}
