### / 1 . - Petición para mostrar todos los productos
GET http://localhost:3000/users


###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "tipo_producto": "ropa interior masc",
  "precio": "10",
  "producto": "slip",
  "imagen": "x"
}

###
PUT http://localhost:3000/products
Content-Type: application/json

{
    "id": "7",
    "tipo_producto": "chaqueta",
    "precio": "200",
    "imagen": "x",
    "producto": "parka the north face"
}

###
DELETE  http://localhost:3000/products/7
Content-Type: application/json


