### / 1 . - Petición para mostrar todos los productos
GET http://localhost:3000/users


###
GET http://localhost:3000/users/2

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombre": "jjjj",
  "apellidos": "jjjjjj",
  "fecha_nacimiento": "2020-10-21",
  "email": "jj@gmail.com",
  "nickname": "pepe",
  "contrasena": "123",
  "confirmar_contrasena": "123",
  "foto": "http",
  "rol": "comprador"

}

###
PUT http://localhost:3000/products
Content-Type: application/json

{
    "id": "7",
    "tipo_producto": "chaqueta",
    "precio": "200",
    "imagen": "x",
    "producto": "parka the north face"
}

###
DELETE  http://localhost:3000/products/7
Content-Type: application/json


